name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'Hello everyone from the pipeline!'

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v2

      - name: Setup Postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: mr_testerson
          postgresql password: pa55w0rd

      - name: Install dependencies
        run: npm install

      - name: Test utils and app
        run: PGDATABASE=test_db PGUSER=mr_testerson PGPASSWORD=pa55w0rd npm test
